config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end

    collection do
      get 'edit_all' # 一括編集画面へのルーティング
      patch 'update_all' # 一括更新アクションへのルーティング
    end

    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update, ]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info,:index]
  before_action :set_one_month, only: :show

  def index
    @users = if params[:search].present?
      @search_word = params[:search]
      User.where("name LIKE ?", "%#{@search_word}%").paginate(page: params[:page])
    else
      @search_word = nil
      User.paginate(page: params[:page])
    end
  end



  def show
    @user = User.find(params[:id])
    if current_user.admin? || current_user?(@user)
      @worked_sum = @attendances.where(user_id: @user.id).where.not(started_at: nil).count
    else
      flash[:danger] = "他のユーザーの情報にアクセスする権限がありません。"
      redirect_to root_url
    end
  end



  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = @user.errors.full_messages.join(", ")
      respond_to do |format|
        format.html { render :new }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("flash", partial: "shared/flash_messages") }
      end
    end
  end


  def edit
  end


  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      flash.now[:danger] = @user.errors.full_messages.join(", ")
      respond_to do |format|
        format.html { render :new }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("flash", partial: "shared/flash_messages") }
      end
    end
  end


  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_all
    # 一括編集の処理を実装
  end

  def update_all
    users = User.all
      new_basic_time = params[:basic_time]
      new_work_time = params[:work_time]
      success = true

      users.each do |user|
        if !user.update(basic_time: new_basic_time, work_time: new_work_time)
          success = false
          break
        end
    end

    if success
      flash.now[:success] = "全ユーザーの基本情報が更新されました。"
    else
      flash.now[:danger] = "更新は失敗しました。"
    end
      redirect_to users_path
  end


  def edit_basic_info
    @user = User.find(params[:id])

    respond_to do |format|
      format.html { render partial: 'users/edit_basic_info', locals: { user: @user } } # 修正
      format.turbo_stream
    end
  end




  def update_basic_info
    if @user.update(basic_info_params)
      flash.now[:success] = "#{@user.name}の基本情報を更新しました!"
    else
      flash.now[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.turbo_stream
    end
  end

  private

  def admin_user
    unless current_user.admin?
      flash[:danger] = "管理者のみがアクセスできます。"
      redirect_to(root_url)
    end
  end

  def set_user
     @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
     flash[:danger] = "削除済み、または存在しないアカウントです。"
     redirect_to root_path

  end

  def user_params
    params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
  end

  def basic_info_params
    params.require(:user).permit(:name, :email, :department, :basic_time, :work_time)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>


<%= turbo_frame_tag 'modal' do %>
  <div class="modal-dialog modal-lg modal-dialog-center" data-controller="edit-basic-info">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-action="edit-basic-info#close" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
        <h1 class="modal-title">基本情報編集</h1>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: false, method: :patch, data: { action: "submit->edit-basic-info#submit" }) do |f| %>              <%= render 'shared/error_messages', object: @user %>
  
              <%= f.label :name, class: "label-#{yield(:class_text)}" %>
              <p><%= @user.name %></p>
  
              <%= f.label :department, class: "label-#{yield(:class_text)}" %>
              <%= f.text_field :department, class: "form-control" %>
  
              <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
              <%= f.time_field :basic_time, class: "form-control" %>
  
              <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
              <%= f.time_field :work_time, class: "form-control" %>
  
              <div class="center">
                <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
                <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-action="edit-basic-info#close">
                  キャンセル
                </button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :名前, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :メールアドレス, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :所属, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :パスワード, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "パスワード確認", class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_search_results.html.erb
<h1><%= @search_word.present? ? '検索結果' : 'ユーザー一覧' %></h1>

<table class="table table-condensed table-hover" id="table-users">
  <thead>
    <tr>
      <th><%= User.human_attribute_name :name %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="actions">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to '基本情報編集', edit_basic_info_user_path(user), data: { turbo_frame: 'modal' }, class: "btn btn-link" %>
            |
            <%= link_to "削除", user, data: { turbo_method: :delete, confirm: "削除してよろしいですか？" }, class: "btn btn-link" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>

<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_all.html.erb
<% provide(:title, "全ユーザーの情報を編集") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集') %>

<% if current_user.admin? %>
  <div class="container text-center">
    <h1>基本情報の更新</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_with(url: update_all_users_path, method: :patch) do |f| %>

         <%= f.label :指定勤務時間, class: "label-#{yield(:class_text)}" %>
         <%= f.time_field :work_time, class: "form-control" %>

         <%= f.label :基本勤務時間, class: "label-#{yield(:class_text)}" %>
         <%= f.time_field :basic_time, class: "form-control" %>
          
         <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% if @search_word.present? %>
  <h1>検索結果</h1>
<% else %>  
  <h1>ユーザー一覧</h1>
<% end %>

 <!-- ユーザー検索フォーム -->
<div class="search-form float-right">
  <%= form_with(url: users_path, method: :get) do |f| %>
    <div class="form-group">
      <%= f.label :search, "ユーザー名で検索" %>
      <%= f.text_field :search, class: "form-control search-input", placeholder: "ユーザー名を入力してください" %>
    </div>
    <%= f.submit "検索", class: "btn btn-primary search-button" %>
  <% end %>
</div>


<div class="clearfix"></div>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <% if current_user.admin? %>
              <%= link_to user.name, user %>
            <% else %>
              <%= user.name %>
            <% end %>
          </td>
          <td class="actions">
            <% if current_user.admin? && !current_user?(user) %>
              <%= link_to '基本情報編集', edit_basic_info_user_path(user), data: { turbo_frame: 'modal' }, class: "btn btn-link" %>
             |<%= link_to "削除", user, data: { turbo_method: :delete, turbo_confirm: "削除してよろしいですか？" }, class: "btn btn-link" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>
<%= @user.errors.full_messages.join(", ") %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr class="nav-row">
      <td>
        <%= link_to "⇦", user_path(date: @first_day.prev_month), class: "btn btn-custom" %>
         <span class="attendance-title">【<%= l(@first_day, format: :middle) %>】時間管理表</span>
        <%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-custom" %>
      </td>
      <td>指定勤務時間：<%= format_basic_info(@user.work_time) %></td>
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>初日：<%= l(@first_day, format: :short) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>出勤日数:<%= @worked_sum %>日</td>
      <td>締め：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

  <div class="button-container">
    <%= link_to "勤怠の編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-custom btn-blue" %>
  </div>    
 
  

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="2">日付</th>
        <th rowspan="2">曜日</th>
        <th colspan="2">出社</th> <!-- 出社の下に時と分のカラム -->
        <th style="width: 200px;"></th>
        <th colspan="2">退社</th> <!-- 退社の下に時と分のカラム -->
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th rowspan="2">残業指示</th>
        <th rowspan="2">指示者</th>
      </tr>
       <tr>
        <th>時</th> <!-- 出社の下に時と分のカラム -->
        <th>分</th> <!-- 退社の下に時と分のカラム -->
        <th></th>
        <th>時</th> <!-- 出社の下に時と分のカラム -->
        <th>分</th> <!-- 退社の下に時と分のカラム -->
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <tr>
         <td><%= l(day.worked_on, format: :short) %></td>
         <td class="<%= 'blue' if day.worked_on.saturday? %> <%= 'red' if day.worked_on.sunday? %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
         <% if day.started_at %>
         <% started_at_hours = day.started_at.hour %>
         <% started_at_minutes = (day.started_at.min / 15) * 15 %>
          <td><%= started_at_hours %></td>
          <td><%= format('%02d', started_at_minutes) %></td>
         <% else %>
          <td></td>
          <td></td>
         <% end %>
          <td>
           <% if btn_text = attendance_state(day) %>
            <%= link_to "#{btn_text}", user_attendance_path(@user, day), data: { turbo_method: :patch }, class: "btn btn-primary btn-attendance btn-text" %>
           <% end %>
          </td>
          <% if day.finished_at %>
          <% finished_at_hours = day.finished_at.hour %>
          <% finished_at_minutes = (day.finished_at.min / 15) * 15 %>
           <td><%= finished_at_hours %></td>
           <td><%= format('%02d', finished_at_minutes) %></td>
          <% else %>
           <td></td>
           <td></td>
          <% end %>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
             <%= str_times = working_times(day.started_at, day.finished_at) %>
             <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= day.overtime_instruction %></td>
          <td><%= day.supervisor %></td>
       </tr>
      <% end %>
    </tbody>

    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="2">累計在社時間</td>
        <td rowspan="2"></td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="2"><%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </tfoot> 
  </table>
</div>

app/views/users/update_basic_info.turbo_stream.erb
<%= turbo_stream.replace 'flash', partial: 'shared/flash_messages' %>